// SCSS
import SideFilter from "../../components/SideFilter"
import SideNavBar from "../../components/SideNavBar"
import "../../styles/global.scss"

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="main">
        <SideNavBar />
        {children}
        <SideFilter />
        </body>
    </html>
  )
}
